export const env = {
    NODE: '/var/lang/bin/node',
    INIT_CWD: '/var/task',
    HOST: '',
    npm_config_metrics_registry: 'https://registry.npmjs.org/',
    ABLY_SESSION_TTL: '1677087524896',
    BUCKET: '',
    REPLICATE_SCALE_VERSION: 'b0bb4c529bb749ac98145e70f42f88d36598e89310beeeba4ee00e14238d1b4d',
    AWS_SESSION_TOKEN: 'IQoJb3JpZ2luX2VjEEEaDGV1LWNlbnRyYWwtMSJHMEUCIQDtGZddU2v+Q8fLKHrydhicA1nGjod9AtCrHW7iCden9gIgVguki+BkVfL07xG+n7X+ptzjfU3x/ZUieMhXUu/2O3YqigMI2///////////ARAAGgwyMTA5MjE2NDMwMjQiDCxeiHV7DuH540hzXyreAtbhTkA71iyTeW8XjC6P1NDvfSrS7JAn24MKv9pGn6Mxdu0pMSD5J3+45l5LWHENJGDXcb0ic6sRRvO1YEOUlFZFOjwXIRVc6pGPEthYdceVg4s+81YHSdCbtinAE+2Jn7O6JQftTY/8iiRanvRt+fZTHOaTuHZH+jTSq/g8+KqMQ8QHQd5JFmJj3FYKm5/G4l+KYyD6+rGsq/1rpjVfBLpE5mtJ1PvVWQPlqhhwlWZjiQHYiLLecD/TPxWmawplEtVy5gorakUdfr5YcLtIthbQzPZtkEuIRqqjVUFNd4hgJ1NxM7VUy6OCndceKyQKshnwJ0bzyJOQddplBD6FtIOtxytwKOHXqhPqDkXchJEGhR1A4GNgRiCTqRznRc2uPSy2kfs2riTNtjg9xwMoYNMQuE1HzPbY7q13jlKtYf0KCMFb8cCBdc37qbpgtIW3RBzlD1QmvCum4aMlY3hUMLWf2Z8GOp4BJBgpYBCTHps77ojXFtqkdrlzQoyXu8ZEIjiKorUpQ6aqVJmsHJBLYS+iPgvjhmqRC1UhHQzrr7XHqnqmlxfIp1AeTrxElpKIze5xq3XWcVwEGPPyL5M80rpTmC8t7i5yj1CntNk1/7ekMhP6i6ebWI6I8wGB6OVhUkNcrnFR1H7ccb4tieTfpiD9ZpzrMJ1T93jCzX75e3BOfdz0y4s=',
    CYCLIC_DB: 'smoggy-tam-boaCyclicDB',
    LD_LIBRARY_PATH: '/var/lang/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib:/opt/lib',
    npm_config_globalconfig: '/var/lang/etc/npmrc',
    CYCLIC_APP_ID: 'smoggy-tam-boa',
    npm_execpath: '/var/lang/lib/node_modules/npm/bin/npm-cli.js',
    PATH: '/var/lang/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/task/node_modules/.bin:/var/lang/bin:/usr/local/bin:/usr/bin/:/bin:/opt/bin',
    npm_config_userconfig: '/home/sbx_user1051/.npmrc',
    npm_config_init_module: '/home/sbx_user1051/.npm-init.js',
    ABLY_KEY: 'W8GHvA.Pb6goQ:yMi6soQ_8VPlsQxt88ekwKluuq_Jg-EYTsC4JOI8080',
    PWD: '/var/task',
    npm_lifecycle_event: 'start',
    AWS_SECRET_ACCESS_KEY: '2gdUoPVWvV9Mg3GUBEJpbDMWFkqmoI9XKr7N5C6m',
    LANG: 'en_US.UTF-8',
    REPLICATE_API_TOKEN: 'e64c92ddbb2f5ad40c9970a96d2cd9f7cd87eaba',
    AWS_REGION: 'eu-central-1',
    TZ: ':UTC',
    NODE_PATH: '/opt/nodejs/node18/node_modules:/opt/nodejs/node_modules:/var/runtime/node_modules:/var/runtime:/var/task',
    REPLICATE_DIFFUSION_VERSION: 'f178fa7a1ae43a9a9af01b833b9d2ecf97b1bcb0acfd2dc5dd04895e042863f1',
    ABLY_SESSION_STREAM_ALL: 'true',
    npm_config_node_gyp: '/var/lang/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
    AWS_ACCESS_KEY_ID: 'ASIATCG7I3QIJSD4ABLT',
    SHLVL: '1',
    npm_config_cache: '/home/sbx_user1051/.npm',
    npm_lifecycle_script: 'node index.js',
    CYCLIC_BUCKET_NAME: 'cyclic-smoggy-tam-boa-eu-central-1',
    npm_config_user_agent: 'linux x64',
    PORT: '3000',
    NODE_EXTRA_CA_CERTS: '/etc/pki/tls/certs/ca-bundle.crt',
    npm_node_execpath: '/var/lang/bin/node',
    npm_config_link: '',
    npm_config_prefix: '/var/lang',
    CYCLIC_URL: 'https://smoggy-tam-boa.cyclic.app',
    _: '/var/lang/bin/node'
  };